export const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2020,
    type: "Sedan",
    availability: true,
    price_per_day: 50,
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2019,
    type: "Sedan",
    availability: false,
    price_per_day: 45,
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    year: 2021,
    type: "Sports Car",
    availability: true,
    price_per_day: 100,
  },
  {
    id: 4,
    make: "Chevrolet",
    model: "Tahoe",
    year: 2020,
    type: "SUV",
    availability: true,
    price_per_day: 80,
  },
  {
    id: 5,
    make: "Jeep",
    model: "Wrangler",
    year: 2018,
    type: "SUV",
    availability: true,
    price_per_day: 90,
  },
];
